version: '2'
services:
  nginx:
    image: gis-photo-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9100:80"
    links:
      - phl-play-django
    volumes:
      # Static Files
      - ./nginx/srv/:/srv/
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf

  database:
    image: quay.io/azavea/postgis:9.5.3
    environment:
      - POSTGRES_USER=playgrounds
      - POSTGRES_PASSWORD=playgrounds
      - POSTGRES_DB=playgrounds

  phl-play-django:
    image: gis-photo-django
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    links:
      - database:database.phlplay.internal
    environment:
      - DB_HOST=database.phlplay.internal
      - DB_NAME=playgrounds
      - DB_PASSWORD=playgrounds
      - DB_PORT=5432
      - DB_USER=playgrounds
      - DJANGO_ENVIRONMENT=development
      - DJANGO_SECRET_KEY=zbx2yavjeh17ibm6ddhidjy8lu7fy0k69
    volumes:
      - ./django/:/opt/phlplay/django/

