# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 18:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=26918)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('address', models.TextField()),
            ],
        ),
    ]
